/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OORestaurants;

import java.awt.Component;
import java.lang.String;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;



/**
 * @author ADITYA
 */
public class OO_Restaurants extends javax.swing.JFrame {

    /**
     * Creates new form OO_Restaurants
     */
    public OO_Restaurants() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        box1 = new javax.swing.JPanel();
        rms = new javax.swing.JLabel();
        pic1 = new javax.swing.JLabel();
        pic2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLtax2 = new javax.swing.JLabel();
        jLSUBTOTAL2 = new javax.swing.JLabel();
        jtxtVanMilkShake = new javax.swing.JTextField();
        jtxtMilkShake = new javax.swing.JTextField();
        jtxtVanliiaCone = new javax.swing.JTextField();
        jLtax4 = new javax.swing.JLabel();
        jLtax5 = new javax.swing.JLabel();
        jLtax6 = new javax.swing.JLabel();
        jtxtClasVanilla = new javax.swing.JTextField();
        jtxtChocoMilkShake = new javax.swing.JTextField();
        jLtax7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        box4 = new javax.swing.JPanel();
        jbtnTotal = new javax.swing.JButton();
        jtxtReceipt = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLtax8 = new javax.swing.JLabel();
        jLtax9 = new javax.swing.JLabel();
        jLtax10 = new javax.swing.JLabel();
        jLtax11 = new javax.swing.JLabel();
        jLtax12 = new javax.swing.JLabel();
        jLtax13 = new javax.swing.JLabel();
        jtxtChickenBurger = new javax.swing.JTextField();
        jtxtChickenLengend = new javax.swing.JTextField();
        jtxtFiletOFish = new javax.swing.JTextField();
        jtxtChickenBurgerM = new javax.swing.JTextField();
        jtxtBaconCheeseBurger = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jtxtTax = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTotal = new javax.swing.JTextField();
        jLtax = new javax.swing.JLabel();
        jLSUBTOTAL = new javax.swing.JLabel();
        jLtotal = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLtax3 = new javax.swing.JLabel();
        jLSUBTOTAL3 = new javax.swing.JLabel();
        jLtotal3 = new javax.swing.JLabel();
        jtxtCostTotalCost = new javax.swing.JTextField();
        jtxtCostDrink = new javax.swing.JTextField();
        jtxtCostMeal = new javax.swing.JTextField();
        jtxtReciept = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtReceipt1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        box1.setBackground(new java.awt.Color(0, 0, 0));
        box1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        rms.setFont(new java.awt.Font("Tahoma", 1, 66)); // NOI18N
        rms.setForeground(new java.awt.Color(255, 255, 255));
        rms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rms.setText("Restaurant Management System");
        rms.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 8));

        pic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pic1.setText("jlabel");
        pic1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 8, true));

        pic2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pic2.setText("jlabel");
        pic2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 8, true));

        javax.swing.GroupLayout box1Layout = new javax.swing.GroupLayout(box1);
        box1.setLayout(box1Layout);
        box1Layout.setHorizontalGroup(
            box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(box1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rms, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        box1Layout.setVerticalGroup(
            box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pic2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(box1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(rms, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pic1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(19, 19, 19))
        );

        getContentPane().add(box1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1380, 160));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jLtax2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLtax2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLtax2.setText("MILK SHAKE");

        jLSUBTOTAL2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLSUBTOTAL2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLSUBTOTAL2.setText("VANlLIA MILK SHAKE");

        jtxtVanMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtVanMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVanMilkShake.setText("0");
        jtxtVanMilkShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtVanMilkShakeActionPerformed(evt);
            }
        });

        jtxtMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtMilkShake.setText("0");
        jtxtMilkShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtMilkShakeActionPerformed(evt);
            }
        });

        jtxtVanliiaCone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtVanliiaCone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtVanliiaCone.setText("0");
        jtxtVanliiaCone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtVanliiaConeActionPerformed(evt);
            }
        });

        jLtax4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLtax4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtax4.setText("DRINKS");

        jLtax5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLtax5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLtax5.setText("VALLINA CONE");

        jLtax6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLtax6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLtax6.setText("CLASSIC VALLINA");

        jtxtClasVanilla.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtClasVanilla.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtClasVanilla.setText("0");
        jtxtClasVanilla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtClasVanillaActionPerformed(evt);
            }
        });

        jtxtChocoMilkShake.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChocoMilkShake.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChocoMilkShake.setText("0");
        jtxtChocoMilkShake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChocoMilkShakeActionPerformed(evt);
            }
        });

        jLtax7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLtax7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLtax7.setText("CHOCOLATE MILKSHAKE");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("ChocoMilkShake");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLSUBTOTAL2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLtax6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLtax2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLtax7, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                            .addComponent(jLtax5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLtax4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtClasVanilla, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(jtxtVanMilkShake, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(jtxtVanliiaCone, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(jtxtMilkShake, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(jtxtChocoMilkShake))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLtax4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLtax2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLtax5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtVanliiaCone, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLtax6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtClasVanilla, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLSUBTOTAL2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jtxtVanMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtChocoMilkShake, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(591, 591, 591)
                .addComponent(jLtax7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 480, 340));

        box4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jbtnTotal.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jbtnTotal.setText("TOTAL");
        jbtnTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTotalActionPerformed(evt);
            }
        });

        jtxtReceipt.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jtxtReceipt.setText("RECEIPT");
        jtxtReceipt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jtxtReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtReceiptActionPerformed(evt);
            }
        });

        jbtnReset.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jbtnReset.setText("RESET");
        jbtnReset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jButton4.setText("EXIT");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout box4Layout = new javax.swing.GroupLayout(box4);
        box4.setLayout(box4Layout);
        box4Layout.setHorizontalGroup(
            box4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(box4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addComponent(jtxtReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129)
                .addComponent(jbtnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        box4Layout.setVerticalGroup(
            box4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, box4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(box4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnTotal)
                    .addComponent(jtxtReceipt)
                    .addComponent(jbtnReset)
                    .addComponent(jButton4))
                .addGap(31, 31, 31))
        );

        getContentPane().add(box4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 710, 970, 80));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jLtax8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLtax8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtax8.setText("MEALS");

        jLtax9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLtax9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLtax9.setText("FILET-O-FISH");

        jLtax10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLtax10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLtax10.setText("CHICKEN BURGER");

        jLtax11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLtax11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLtax11.setText("CHICKEN LEGEND");

        jLtax12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLtax12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLtax12.setText("CHICKEN BURGER MEAL");

        jLtax13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLtax13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLtax13.setText("BACON AND CHEESE BURGER");

        jtxtChickenBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenBurger.setText("0");
        jtxtChickenBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChickenBurgerActionPerformed(evt);
            }
        });

        jtxtChickenLengend.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenLengend.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenLengend.setText("0");
        jtxtChickenLengend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChickenLengendActionPerformed(evt);
            }
        });

        jtxtFiletOFish.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtFiletOFish.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtFiletOFish.setText("0");
        jtxtFiletOFish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFiletOFishActionPerformed(evt);
            }
        });

        jtxtChickenBurgerM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtChickenBurgerM.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtChickenBurgerM.setText("0");

        jtxtBaconCheeseBurger.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtBaconCheeseBurger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtBaconCheeseBurger.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLtax8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLtax9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLtax10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLtax11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLtax12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLtax13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtChickenBurgerM)
                            .addComponent(jtxtFiletOFish)
                            .addComponent(jtxtChickenBurger)
                            .addComponent(jtxtChickenLengend, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jtxtBaconCheeseBurger))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLtax8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLtax9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtFiletOFish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLtax10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtChickenBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLtax11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtChickenLengend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLtax12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLtax13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jtxtChickenBurgerM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtxtBaconCheeseBurger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 480, 340));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jtxtTax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTax.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtxtTax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTaxActionPerformed(evt);
            }
        });

        jtxtSubTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });

        jtxtTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });

        jLtax.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLtax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtax.setText("TAX");

        jLSUBTOTAL.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLSUBTOTAL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSUBTOTAL.setText("SUBTOTAL");

        jLtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLtotal.setText("TOTAL");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLtax, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtTax, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLSUBTOTAL, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(155, 155, 155)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLtax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtTax))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtSubTotal)
                    .addComponent(jLSUBTOTAL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtTotal)
                    .addComponent(jLtotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, 480, 180));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jLtax3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLtax3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLtax3.setText("COST OF MEALS ");
        jLtax3.setToolTipText("");

        jLSUBTOTAL3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLSUBTOTAL3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLSUBTOTAL3.setText("COST OF DRINKS");

        jLtotal3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLtotal3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLtotal3.setText("Total Cost  of Items");

        jtxtCostTotalCost.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCostTotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCostTotalCostActionPerformed(evt);
            }
        });

        jtxtCostDrink.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCostDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCostDrinkActionPerformed(evt);
            }
        });

        jtxtCostMeal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtCostMeal.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        jtxtCostMeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtCostMealActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLtax3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(jtxtCostMeal, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLtotal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLSUBTOTAL3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtCostTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtCostDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtCostMeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLtax3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtCostDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSUBTOTAL3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtCostTotalCost)
                    .addComponent(jLtotal3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 480, 180));

        jtxtReciept.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 12));

        jtxtReceipt1.setColumns(20);
        jtxtReceipt1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jtxtReceipt1.setRows(5);
        jScrollPane1.setViewportView(jtxtReceipt1);

        javax.swing.GroupLayout jtxtRecieptLayout = new javax.swing.GroupLayout(jtxtReciept);
        jtxtReciept.setLayout(jtxtRecieptLayout);
        jtxtRecieptLayout.setHorizontalGroup(
            jtxtRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jtxtRecieptLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jtxtRecieptLayout.setVerticalGroup(
            jtxtRecieptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jtxtRecieptLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jtxtReciept, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 170, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtTaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTaxActionPerformed

    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jtxtCostTotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCostTotalCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCostTotalCostActionPerformed

    private void jtxtCostDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCostDrinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCostDrinkActionPerformed

    private void jtxtCostMealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtCostMealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtCostMealActionPerformed

    private void jtxtChocoMilkShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChocoMilkShakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChocoMilkShakeActionPerformed

    private void jtxtClasVanillaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtClasVanillaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtClasVanillaActionPerformed

    private void jtxtVanliiaConeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtVanliiaConeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtVanliiaConeActionPerformed

    private void jtxtMilkShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtMilkShakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtMilkShakeActionPerformed

    private void jtxtVanMilkShakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtVanMilkShakeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtVanMilkShakeActionPerformed

    private void jtxtChickenBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChickenBurgerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChickenBurgerActionPerformed

    private void jtxtChickenLengendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChickenLengendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChickenLengendActionPerformed

    private void jtxtFiletOFishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFiletOFishActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFiletOFishActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        SubClass_Child iExit = new SubClass_Child();
        iExit.iExitSystem();
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        JTextField cleartext = null;
        
        
        for (Component c:jPanel1.getComponents()){
            if(c.getClass().toString().contains("javax.swing.Jtextfield")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
         //===============================================================================================   
        }
         
        for (Component c:jPanel3.getComponents()){
            if(c.getClass().toString().contains("javax.swing.Jtextfield")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
         //===============================================================================================
        }  
        for (Component c:jPanel5.getComponents()){
            if(c.getClass().toString().contains("javax.swing.Jtextfield")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
         //===============================================================================================   
        }
         
        for (Component c:jPanel7.getComponents()){
            if(c.getClass().toString().contains("javax.swing.Jtextfield")){
                cleartext = (JTextField)c;
                cleartext.setText("0");
            }
        }
        //=================================================================================================
        jtxtReceipt1.setText(null);
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jtxtReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtReceiptActionPerformed
        
        //=============================================================================
        int refs = 1325 +(int) (Math.random()*4238);
        
        //=============================================================================
        
        
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat Tdate = new SimpleDateFormat("dd-MM-yyyy");
        Tdate.format(timer.getTime());
                      jtxtReceipt1.append("\tRestaurant Management System:\n"  +
                              "reference:\t\t\t" + refs +
                      "\n============================================\n"  +
                              "Meals:\t\t\t" + jtxtCostMeal.getText() + "\n\n" +
                              "Drinks:\t\t\t" + jtxtCostDrink.getText()+ "\n\n" +
                              "Cost of Items:\t\t\t" + jtxtCostTotalCost.getText() +"\n\n" +
                              "========================================="  + "\n\n" + 
                              "Tax:\t\t" + jtxtTax.getText() + "\n\n" +
                              "SubTotal:\t" + jtxtSubTotal.getText() + "\n\n" +
                              "Total:\t\t" + jtxtTotal.getText() + "\n\n" + 
                              "===========================================" +
                              "nDate:" +Tdate.format(timer.getTime())+
                              "\tTime: " + tTime.format(timer.getTime()) +
                              "\n\n\t\t thank you!" );
                              
 
         
        
        
    }//GEN-LAST:event_jtxtReceiptActionPerformed

    private void jbtnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTotalActionPerformed
        SubClass_Child ItemCost = new SubClass_Child();
        double iTax, iSubTotal , iTotal;
        
        ItemCost.Filet_O_Fish= ItemCost.pFilet_O_Fish  * Double.parseDouble(jtxtFiletOFish.getText());
        ItemCost.ChickenBurger = ItemCost.pChickenBurger * Double.parseDouble(jtxtChickenBurger.getText());
        ItemCost.ChickenLengend = ItemCost.pChickenLengend * Double.parseDouble(jtxtChickenLengend.getText());
        ItemCost.pChickenBurgerM = ItemCost.pChickenBurgerM * Double.parseDouble(jtxtChickenBurgerM.getText());
        ItemCost.BaconCheeseBurger = ItemCost.pBaconCheeseBurger * Double.parseDouble(jtxtBaconCheeseBurger.getText());
       
        ItemCost.MilkShake= ItemCost.pMilkShake  * Double.parseDouble(jtxtMilkShake.getText());
        ItemCost.VanliiaCone= ItemCost.pVanliiaCone  * Double.parseDouble(jtxtVanliiaCone.getText());
        ItemCost.ClasVanilla = ItemCost.pClasVanilla   * Double.parseDouble(jtxtClasVanilla.getText());
        ItemCost.VanMilkShake= ItemCost.VanMilkShake  * Double.parseDouble(jtxtVanMilkShake.getText());
        ItemCost.ChocoMilkShake= ItemCost.pFilet_O_Fish  * Double.parseDouble(jtxtChocoMilkShake.getText());
        
        
        iSubTotal = ItemCost.GetAmount();
        iTax = ItemCost.cFindTax(iSubTotal);
        iTotal = iSubTotal + iTax; 
        
        String SubTotal= String.format("$%.2f", iSubTotal);
        jtxtSubTotal.setText(SubTotal);
        
        String Tax= String.format("$%.2f", iTax);
        jtxtTax.setText(Tax);
        
        String Total= String.format("$%.2f", iTotal);
        jtxtTotal.setText(Total);
        
        String Meal= String.format("$%.2f",ItemCost.Meals);
        jtxtCostMeal.setText(Meal);
        
        String Drink= String.format("$%.2f",ItemCost.Drinks);
        jtxtCostDrink.setText(Drink);
        
        String TotalCost= String.format("$%.2f",ItemCost.TotalofMD);
        jtxtCostTotalCost.setText(TotalCost);
    }//GEN-LAST:event_jbtnTotalActionPerformed

        
    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OO_Restaurants.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UIManager.setLookAndFeel("com.jtattoo.plaf.aluminium.AluminiumLookAndFeel");
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OO_Restaurants().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel box1;
    private javax.swing.JPanel box4;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLSUBTOTAL;
    private javax.swing.JLabel jLSUBTOTAL2;
    private javax.swing.JLabel jLSUBTOTAL3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLtax;
    private javax.swing.JLabel jLtax10;
    private javax.swing.JLabel jLtax11;
    private javax.swing.JLabel jLtax12;
    private javax.swing.JLabel jLtax13;
    private javax.swing.JLabel jLtax2;
    private javax.swing.JLabel jLtax3;
    private javax.swing.JLabel jLtax4;
    private javax.swing.JLabel jLtax5;
    private javax.swing.JLabel jLtax6;
    private javax.swing.JLabel jLtax7;
    private javax.swing.JLabel jLtax8;
    private javax.swing.JLabel jLtax9;
    private javax.swing.JLabel jLtotal;
    private javax.swing.JLabel jLtotal3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnTotal;
    private javax.swing.JTextField jtxtBaconCheeseBurger;
    private javax.swing.JTextField jtxtChickenBurger;
    private javax.swing.JTextField jtxtChickenBurgerM;
    private javax.swing.JTextField jtxtChickenLengend;
    private javax.swing.JTextField jtxtChocoMilkShake;
    private javax.swing.JTextField jtxtClasVanilla;
    private javax.swing.JTextField jtxtCostDrink;
    private javax.swing.JTextField jtxtCostMeal;
    private javax.swing.JTextField jtxtCostTotalCost;
    private javax.swing.JTextField jtxtFiletOFish;
    private javax.swing.JTextField jtxtMilkShake;
    private javax.swing.JButton jtxtReceipt;
    private javax.swing.JTextArea jtxtReceipt1;
    private javax.swing.JPanel jtxtReciept;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    private javax.swing.JTextField jtxtVanMilkShake;
    private javax.swing.JTextField jtxtVanliiaCone;
    private javax.swing.JLabel pic1;
    private javax.swing.JLabel pic2;
    private javax.swing.JLabel rms;
    // End of variables declaration//GEN-END:variables
}
